### ISSUE TITLE
Application crashes when opening a domoticz DB

### ISSUE THREAD

**Issue by stevenvanryckeghem** [Johanbos/home-assistant-import#190]
Same issue as #174. In this case Dependabot undid the fix.

**Comment by the-master006** [comment]
Same issue with my domoticz database

**Comment by Johanbos** [comment]
Fixed with the latest release https://github.com/Johanbos/home-assistant-import/releases/tag/v0.2.1-ci.17. Upgrading to Electron fixed https://github.com/WiseLibs/better-sqlite3/issues/1044.

For some reason the version number is lower..... Oops. Removed all older releases to prevent confusion and created #196.
